Algorithms/Models/DynamicConnectivityModel.cs
using Algorithms.Controllers;
using System.ComponentModel.DataAnnotations;

namespace Algorithms.Models
{
    public class DynamicConnectivityModel
    {
        [Display(Name = "Elements Count")]
        public int elementsCount { get; set; }
        public int[] collection { get; set; }
        public string unions { get; set; }
        public int firstNode { get; set; }
        public int secondNode { get; set; }
        public bool connected { get; set; }
    }
}

Algorithms/Models/ErrorViewModel.cs
using System;

namespace Algorithms.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Algorithms/Controllers/DynamicConnectivityController.cs
using Algorithms.Algorithms;
using Algorithms.Models;
using Microsoft.AspNetCore.Mvc;

namespace Algorithms.Controllers
{
    public class DynamicConnectivityController : Controller
    {
        public IActionResult Index(DynamicConnectivityModel model)
        {
            if (ModelState.IsValid && model.elementsCount > 0)
            {
                QuickFind quickFind = new QuickFind(model.elementsCount);

                if (model.unions != null)
                {
                    string[] pairStrings = model.unions.Split("\r\n");
                    string[] pair = new string[2];

                    for (int i = 0; i < pairStrings.Length; i++)
                    {
                        pair = pairStrings[i].Split(" ");
                        int.TryParse(pair[0], out int a);
                        int.TryParse(pair[1], out int b);
                        quickFind.Union(a, b);
                    }
                }

                model.collection = quickFind.array;
            }
            else model.elementsCount = 10;

            return View(model);
        }


        
    }
}

Algorithms/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Algorithms.Models;

namespace Algorithms.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Algorithms/ViewComponents/GraphicViewComponent.cs
using Microsoft.AspNetCore.Html;
using System;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.IO;
using System.Text.Encodings.Web;

namespace Algorithms.ViewComponents
{
    public class GraphicViewComponent : IDisposable
    {
        SolidBrush ellipseBrush = new SolidBrush(Color.White);
        SolidBrush nodeBrush = new SolidBrush(Color.Black);
        Pen pen = new Pen(Color.Black, 1);

        public void Dispose()
        {
            ellipseBrush.Dispose();
            nodeBrush.Dispose();
            pen.Dispose();
        }

        public IHtmlContent Invoke(int[] nodes)
        {
            Point[] points = new Point[nodes.Length];
            int x = 6;
            int y = 15;

            var result = new InlineImageResult(1000, 200);
            for (int i = 0; i < points.Length; i++)
            {
                if (i % 4 == 0)
                {
                    y += 50;
                    x = 30;
                }

                points[i].X += x;
                points[i].Y = y;

                x += 100;
            }

            result.Graphics.DrawLines(pen, points);

            for (int i = 0; i < points.Length; i++)
            {
                result.Graphics.DrawEllipse(pen, points[i].X - 6, points[i].Y - 15, 29, 29);
                result.Graphics.FillEllipse(ellipseBrush, points[i].X - 6, points[i].Y - 15, 29, 29);
                result.Graphics.DrawString(i.ToString(), new Font("Verdana", 20, FontStyle.Regular, GraphicsUnit.Pixel), nodeBrush, points[i].X, points[i].Y - 15);
            }


            return result;
        }
    }

    public sealed class InlineImageResult : IHtmlContent
    {
        private readonly Image bmp;
        public Graphics Graphics { get; private set; }

        public InlineImageResult(Int32 width, Int32 height)
        {
            //the PixelFormat argument is required if we want to have transparency
            this.bmp = new Bitmap(width, height, PixelFormat.Format32bppArgb);

            this.Graphics = Graphics.FromImage(this.bmp);

            //for higher quality
            this.Graphics.CompositingQuality = CompositingQuality.HighQuality;
            this.Graphics.SmoothingMode = SmoothingMode.HighQuality;
            this.Graphics.InterpolationMode = InterpolationMode.High;

            //make the background transparent
            this.Graphics.Clear(Color.Transparent);
        }

        public void WriteTo(TextWriter writer, HtmlEncoder encoder)
        {
            using (this.bmp)
            using (this.Graphics)

            using (var stream = new MemoryStream())
            {
                var format = ImageFormat.Png;
                this.bmp.Save(stream, format);
                var img = String.Format("<img src=\"data:image/{0};base64,{1}\"/>", format.ToString().ToLower(), Convert.ToBase64String(stream.ToArray()));
                writer.Write(img);
            }
        }
    }
}

Algorithms/Views/DynamicConnectivity/Index.cshtml
@model DynamicConnectivityModel

@{
    ViewData["Title"] = "Index";
}

<h1>Dynamic Connectivity</h1>

@using (Html.BeginForm())
{
    @Html.TextBoxFor(m => m.elementsCount, new { @class = "form-control" })

    <hr />

    @Html.TextAreaFor(m => m.unions, new { @class = "form-control" })

    <br />
    <p>

        <div>
            @{
                if (Model.collection != null)
                {
                    @await Component.InvokeAsync("Graphic", new { nodes = Model.collection })
                }
            }
        </div>

    </p>

    <input type = "submit" value = "Process" class="btn btn-primary"/>
}

Algorithms/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Algorithms/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Algorithms</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Algorithms</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DynamicConnectivity" asp-action="Index">Dynamic Connectivity</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Algorithms - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>